### ISSUE TITLE
ECS. Connection reset after prolonged downloading

### ISSUE THREAD

**Issue by levan92** [dhmlops/mlops#9]
My clearml job downloads 50 zip files through `boto3`. However, error is thrown: "ConnectionResetError: [Errno 104] Connection reset by peer", halfway through the downloads. 

This has consistently happened over repeated job runs (see lfn project on clearml, "co3d_2gpu_all" & associated clones). Error occurs at different zip files for different runs. I've double checked the zip files has no issue. 

Each zip file is between 1.5 to 70 GB (average 27GB) each. Error typically occurs in the middle, around after 500GB has been downloaded.

**Comment by mantaphytoplankton** [comment]
And the multipart file transfer is also disabled right?

**Comment by levan92** [comment]
oh hmm, let me try! This is download though, not upload

**Comment by mantaphytoplankton** [comment]
Okay, I will try to reproduce the error tomorrow using S3 browser. And send the logs to Dell support. Please give us abit more time to solve this and the previous issues.  Thanks.

**Comment by mantaphytoplankton** [comment]
@levan92 Not sure if the latest ECS upgrade would have solved this issue. Any way to test?

**Comment by levan92** [comment]
Sorry for the delay, sorry I can't consistently reproduce the error these days. Seems much stable (& faster now).

**Comment by mantaphytoplankton** [comment]
Thanks. Let's reopen this if issue surfaces again.
